Repository konveyor/move2kube-operator, pull requests merged in 2020-12, with the labels that each got.

#22 fix: release workflow to match cli release workflow
  .github/workflows/assignproject.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  .grenrc.js
Labels: bug

#24 fix: typo in slack notification and reformat workflow files
  .github/workflows/assignproject.yml
  .github/workflows/build.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
Labels: bug

#25 fix: ingress host and secret to be more generic
  helm-charts/move2kube/values.yaml
Labels: bug

#27 feat: label pull requests based on their title
  .github/workflows/labelpr.yml
Labels: enhancement

#28 fix: Change default dir for move2kube image to workspace
  helm-charts/move2kube/templates/move2kubeapi-statefulset.yaml
Labels: fix

#29 ci: clean up workflows to work together across multiple repos
  .github/workflows/build.yml
  .github/workflows/labelpr.yml
  .github/workflows/prbuild.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  .grenrc.js
Labels: ci

#30 feat: Support executing podman inside api container
  helm-charts/move2kube/templates/move2kubeapi-statefulset.yaml
Labels: feat

#31 fix: Support privileged containers in Openshift using scc
  helm-charts/move2kube/templates/move2kube-scc.yaml
Labels: fix

#32 ci: fix bug where the 2 args were being treated as a single arg and passed to GREN
  .github/workflows/release.yml
Labels: ci

#33 ci: fix bug the branch name refs/heads/main is being used instead of the tag
  .github/workflows/release.yml
Labels: ci

#34 ci: see https://github.com/konveyor/move2kube/pull/371 for details
  .github/workflows/release.yml
Labels: ci
